### ISSUE TITLE
Returning Observables in Angular

### ISSUE THREAD

**Issue by gagakk** [gagakk/tour-of-heroes#10]
Observable is one of the key classes in the [RxJS library](https://rxjs.dev/).

https://angular.io/tutorial/tour-of-heroes/toh-pt4

**Comment by Prasannajaga** [comment]
HI gagakk,I can help you with the returning observables and issues that you have raised if you let me know what is the purpose

**Comment by gagakk** [comment]
#11 pull request attached.

**Comment by gagakk** [comment]
@Prasannajaga I believe I am good. But thanks for the offer. I am learning Angular and also trying GitHub copilot.

**Comment by Prasannajaga** [comment]
that's good! I saw an open issue of yours. thought of lending my support and I'm currently searching for the open source contribution. if you want any help regarding your projects please let me know. Thanks!
